name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: scheduler
          POSTGRES_PASSWORD: scheduler
          POSTGRES_DB: 123456
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      PG_DSN: postgresql://scheduler:123456@localhost:5432/scheduler?sslmode=disable

    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go mod tidy

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432; then
              echo "Postgres is ready!"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run tests
        run: go test -run ^TestApp$ ./tests
        env:
          TODO_PORT: 7540
          PG_DSN: ${{ env.PG_DSN }}